# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Список пользователей', 'verbose_name_plural': 'Списки пользователей'},
        ),
    ]
