# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170323_2208'),
        ('login', '0002_auto_20170322_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_of_work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_work'),
            preserve_default=False,
        ),
    ]
