# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=300)),
                ('inventory_number', models.IntegerField()),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='groups_of_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='groups_of_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.workspace'),
        ),
    ]
