# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issues',
            fields=[
                ('number_issue', models.IntegerField(primary_key=True, serialize=False)),
                ('brief_description', models.CharField(max_length=200)),
                ('start_down_date', models.DateField()),
                ('start_down_time', models.TimeField()),
                ('start_issue_date', models.DateField()),
                ('start_issue_time', models.TimeField()),
                ('progress', models.CharField(max_length=1000)),
                ('number_history', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_down_date', models.DateField(blank=True, null=True)),
                ('close_down_time', models.TimeField(blank=True, null=True)),
                ('close_issue_date', models.DateField(blank=True, null=True)),
                ('close_issue_time', models.TimeField(blank=True, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_coordinator', to='login.UserProfile', verbose_name='Координатор')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to='login.UserProfile', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name_plural': 'Инциденты',
                'verbose_name': 'Инцидент',
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='groups_of_work',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user_edit',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='id_state',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='user_edit',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Список оборудования', 'verbose_name_plural': 'Списки оборудования'},
        ),
        migrations.AlterModelOptions(
            name='groups_of_reason',
            options={'verbose_name': 'Группа причин', 'verbose_name_plural': 'Группы причин'},
        ),
        migrations.AlterModelOptions(
            name='groups_of_work',
            options={'verbose_name': 'Список рабочих групп', 'verbose_name_plural': 'Списки рабочих групп'},
        ),
        migrations.AlterModelOptions(
            name='level_issue',
            options={'verbose_name': 'Уровень инцидента', 'verbose_name_plural': 'Уровни инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='solutions',
            options={'verbose_name': 'Способ устранения', 'verbose_name_plural': 'Способы устранения'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Словарь статусов сотрудников', 'verbose_name_plural': 'Словари статусов сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='status_issue',
            options={'verbose_name': 'Статус инцидентов', 'verbose_name_plural': 'Статусы инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Список подразделений', 'verbose_name_plural': 'Списки подразделений'},
        ),
        migrations.AlterModelManagers(
            name='equipment',
            managers=[
                ('e_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level_issue',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='groups_of_reason',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups_of_work',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='level_issue',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status_issue',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='issue',
        ),
        migrations.DeleteModel(
            name='workers',
        ),
        migrations.AddField(
            model_name='issues',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.status_issue'),
        ),
        migrations.AddField(
            model_name='issues',
            name='equipment_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.equipment', verbose_name='Инвентарный №'),
        ),
        migrations.AddField(
            model_name='issues',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.equipment', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='issues',
            name='equipment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.equipment', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='issues',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_executor', to='login.UserProfile', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='issues',
            name='group_of_reason',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_reason'),
        ),
        migrations.AddField(
            model_name='issues',
            name='groups_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_work'),
        ),
        migrations.AddField(
            model_name='issues',
            name='level_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.level_issue'),
        ),
        migrations.AddField(
            model_name='issues',
            name='solution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.solutions'),
        ),
        migrations.AddField(
            model_name='issues',
            name='user_edit',
            field=models.ForeignKey(default=manager.models.uknown_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.workspace'),
        ),
    ]
