# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='description',
            new_name='description_state',
        ),
        migrations.AddField(
            model_name='level_issue',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
