# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170222_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='reason',
            new_name='solution',
        ),
        migrations.AddField(
            model_name='issue',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='group_of_reason',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups_of_reason',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups_of_work',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='level_issue',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status_issue',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workers',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
