# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170321_1923'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equipment',
            managers=[
            ],
        ),
    ]
