# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170225_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
