# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170225_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
