# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_issue_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='status',
            new_name='status_issue',
        ),
    ]
