# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170225_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='status_issue',
            new_name='current_status',
        ),
    ]
