# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170225_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='issue',
            name='group_of_reason',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_reason'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.solutions'),
        ),
    ]
