# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170225_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='level_issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.level_issue'),
            preserve_default=False,
        ),
    ]
