# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_issue_level_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Список оборудования', 'verbose_name_plural': 'Списки оборудования'},
        ),
        migrations.AlterModelOptions(
            name='groups_of_reason',
            options={'verbose_name': 'Группа причин', 'verbose_name_plural': 'Группы причин'},
        ),
        migrations.AlterModelOptions(
            name='groups_of_work',
            options={'verbose_name': 'Список рабочих групп', 'verbose_name_plural': 'Списки рабочих групп'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Инцидент', 'verbose_name_plural': 'Инциденты'},
        ),
        migrations.AlterModelOptions(
            name='level_issue',
            options={'verbose_name': 'Уровень инцидента', 'verbose_name_plural': 'Уровни инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='solutions',
            options={'verbose_name': 'Способ устранения', 'verbose_name_plural': 'Способы устранения'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Словарь статусов сотрудников', 'verbose_name_plural': 'Словари статусов сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='status_issue',
            options={'verbose_name': 'Статус инцидентов', 'verbose_name_plural': 'Статусы инцидентов'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Список сотрудников', 'verbose_name_plural': 'Списки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Список подразделений', 'verbose_name_plural': 'Списки подразделений'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='equipment',
        ),
        migrations.AddField(
            model_name='issue',
            name='equipment_inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_inventory', to='manager.equipment', verbose_name='Инвентарный №'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='equipment_model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model', to='manager.equipment', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='equipment_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_name', to='manager.equipment', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
