# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0010_auto_20170226_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='issues',
            fields=[
                ('number_issue', models.IntegerField(primary_key=True, serialize=False)),
                ('brief_description', models.CharField(max_length=200)),
                ('start_down_date', models.DateField()),
                ('start_down_time', models.TimeField()),
                ('start_issue_date', models.DateField()),
                ('start_issue_time', models.TimeField()),
                ('progress', models.CharField(max_length=1000)),
                ('number_history', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_down_date', models.DateField()),
                ('close_down_time', models.TimeField()),
                ('close_issue_date', models.DateField()),
                ('close_issie_time', models.TimeField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_coordinator', to='manager.workers', verbose_name='Координатор')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to='manager.workers', verbose_name='Инициатор')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.status_issue')),
                ('equipment_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_inventory', to='manager.equipment', verbose_name='Инвентарный №')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model', to='manager.equipment', verbose_name='Модель')),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_name', to='manager.equipment', verbose_name='Тип')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_executor', to='manager.workers', verbose_name='Исполнитель')),
                ('group_of_reason', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_reason')),
                ('groups_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.groups_of_work')),
                ('level_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.level_issue')),
                ('solution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.solutions')),
                ('user_edit', models.ForeignKey(default=manager.models.uknown_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.workspace')),
            ],
            options={
                'verbose_name_plural': 'Инциденты',
                'verbose_name': 'Инцидент',
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='equipment_inventory',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='equipment_model',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='group_of_reason',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='groups_of_work',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='level_issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user_edit',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='issue',
        ),
    ]
